# https://github.com/julia-actions/cache#usage
name: CI

on:
  push:
    paths-ignore:
      - README.md
      - 'docs/**'
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.12.5]         # 2026-02-09
        julia-arch: [x64]
        os: [ubuntu-latest]
        include:
          - julia-version: nightly
            os: ubuntu-latest
          - julia-version: 1.11.9       # 2026-02-08
            os: ubuntu-latest
          - julia-version: 1.6.7        # 2022-07-20
            os: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
    - uses: julia-actions/cache@v1
    - uses: julia-actions/julia-buildpkg@v1
    - uses: julia-actions/julia-runtest@v1
    - name: versioninfo
      run: |
           julia -e 'using InteractiveUtils; versioninfo(); dump(Base.GIT_VERSION_INFO)'

  RunJETLS:
    needs: Test
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: aviatesk/JETLS.jl/.github/actions/check@release
      with:
        files: src/Jive.jl test/runtests.jl
        exit-severity: error
        show-severity: warn

  RunMoreTests:
    needs: Test
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v1
    - uses: julia-actions/cache@v1
    - uses: julia-actions/julia-buildpkg@v1
    - name: RunMoreTests
      run: |
           JULIA_TEST_VERBOSE=true julia --color=yes -e 'using Pkg; Pkg.develop("Jive"); Pkg.develop(url="https://github.com/wookay/TestJiveRunMoreTests.jl"); Pkg.test("TestJiveRunMoreTests")'

  RunForMacOS:
    needs: RunMoreTests
    if: github.event.ref == 'refs/heads/master'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - name: versioninfo
        run: |
             julia -e 'using InteractiveUtils; versioninfo(); dump(Base.GIT_VERSION_INFO)'

  RunForWindows:
    needs: RunMoreTests
    if: github.event.ref == 'refs/heads/master'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - name: versioninfo
        run: |
             julia -e 'using InteractiveUtils; versioninfo(); dump(Base.GIT_VERSION_INFO)'

  RunForJulia154:
    needs: RunMoreTests
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.5.4 # 2021-03-11
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - name: versioninfo
        run: |
             julia -e 'using InteractiveUtils; versioninfo(); dump(Base.GIT_VERSION_INFO)'

  Coverage:
    needs: RunMoreTests
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
